### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by vieirafrancisco** [lfnd0/web-development-CICA#1]
Tudo bem, @lfnd0 ?

Ficou muito bom teu projeto. Gostaria de ressaltar algumas coisas:

- Faltou alguma informação na documentação sobre a variável de ambiente para o `SECRET_KEY`. Poderia adicionar uma informação simples como `export SECRET_KEY=alguma_key` ou você poderia adicionar um arquivo `.env` para colocar essas variáveis de ambiente.
- Eu fiquei com uma dúvida com relação ao field `Schedules.timetable`, porque tentei adicionar uma tupla para o Scheduler e sempre tenho que escrever o timestamp por completo, caso eu cometesse algum erro ele me bloqueia na validação. Ai no caso você espera um timestamp vindo do frontend?

**Comment by lfnd0** [comment]
> Tudo bem, @ lfnd0 ?
> 
> Ficou muito bom teu projeto. Gostaria de ressaltar algumas coisas:
> 
> * Faltou alguma informação na documentação sobre a variável de ambiente para o `SECRET_KEY`. Poderia adicionar uma informação simples como `export SECRET_KEY=alguma_key`ou você poderia adicionar um arquivo `.env`para colocar essas variáveis ​​de ambiente.
> * Eu fiquei com uma dúvida em relação ao campo `Schedules.timetable`, porque tentei adicionar uma tupla para o Scheduler e sempre tenho que escrever o timestamp por completo, caso eu cometesse algum erro ele me bloqueia na validação. Ai no caso você espera um timestamp vindo do frontend?

> Olá @vieirafrancisco !

**Comment by lfnd0** [comment]
Olá @vieirafrancisco irei ver todas as tuas sugestões e acrescentá-las ao projeto. Obrigado pelo feedback!

**Comment by lfnd0** [comment]
> Tudo bem, @lfnd0 ?
> 
> Ficou muito bom teu projeto. Gostaria de ressaltar algumas coisas:
> 
> * Faltou alguma informação na documentação sobre a variável de ambiente para o `SECRET_KEY`. Poderia adicionar uma informação simples como `export SECRET_KEY=alguma_key` ou você poderia adicionar um arquivo `.env` para colocar essas variáveis de ambiente.
> * Eu fiquei com uma dúvida com relação ao field `Schedules.timetable`, porque tentei adicionar uma tupla para o Scheduler e sempre tenho que escrever o timestamp por completo, caso eu cometesse algum erro ele me bloqueia na validação. Ai no caso você espera um timestamp vindo do frontend?

**Comment by lfnd0** [comment]
> Tudo bem, @lfnd0 ?
> 
> Ficou muito bom teu projeto. Gostaria de ressaltar algumas coisas:
> 
> * Faltou alguma informação na documentação sobre a variável de ambiente para o `SECRET_KEY`. Poderia adicionar uma informação simples como `export SECRET_KEY=alguma_key` ou você poderia adicionar um arquivo `.env` para colocar essas variáveis de ambiente.
> * Eu fiquei com uma dúvida com relação ao field `Schedules.timetable`, porque tentei adicionar uma tupla para o Scheduler e sempre tenho que escrever o timestamp por completo, caso eu cometesse algum erro ele me bloqueia na validação. Ai no caso você espera um timestamp vindo do frontend?

> Sem querer fechei a issue, ignora esse deslize, tá? rsrs.
